### ISSUE TITLE
add foundation_types

### ISSUE THREAD

**Issue by zanhosit** [Zanhos/FunderMaps#7]
Add foundation_types

 **Extra type of "shallow foundation" (steel);**
- masonry (gemetseld)
- strips of foundation (stroken fundering)
- foundation bearing floor ( fundering met dragen vloer)
- load-bearing concrete floor (dragende betonvloer)
- slit (slieten)

 **Extra type of foundations "wooden pile foundation"** 
- Amsterdam foundation
- Rotterdam foundation

**Comment by yorickdewid** [comment]
**no_pile**
- masonry (gemetseld)
- strips of foundation (stroken fundering)
- foundation bearing floor ( fundering met dragen vloer)
- load-bearing concrete floor (dragende betonvloer)
- slit (slieten)

 **wood** 
- Amsterdam foundation
- Rotterdam foundation
